title: decuser's blog
author:
  name: decuser
  email: will.senn@gmail.com
description: decuser's technical explorations and adventures in retro-computing, unix, and
  programming.

show_excerpts: true
excerpt_separator: <!--more-->

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/decuser" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@decuser" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate

paginate: 10 
timezone: America/Chicago
